[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#4B71FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2329"
textColor = "#FAFAFA"
font = "sans serif"

[client]
showSidebarNavigation = false
